Attendace-Face-Recognition-Web-App/website/views.py
import datetime
from distutils.log import error, info
from email import message
from sys import modules
from cv2 import CAP_PROP_AUTO_EXPOSURE
from numpy import roll
from website.face_detection import detect_faces, get_face_box
from website.face_recognition import preform_face_recognition
from website.utility_functions import *
from sched import scheduler
from flask import Blueprint, Response, copy_current_request_context, render_template, request, session, url_for, current_app, flash, jsonify, redirect
from flask_login import login_required, current_user
from .models import Student, Attendance, Module
from sqlalchemy import exc
from . import db
import json
from werkzeug.utils import secure_filename
import os
import random
import cv2
import csv
import threading
from flask_apscheduler import APScheduler


# Webcam resolution adjustment
#web_cam = cv2.VideoCapture(1, cv2.CAP_DSHOW)
web_cam = cv2.VideoCapture(1)
web_cam.set(cv2.CAP_PROP_FPS, 40.0)
web_cam.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter.fourcc('m', 'j', 'p', 'g'))
web_cam.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter.fourcc('M', 'J', 'P', 'G'))
web_cam.set(cv2.CAP_PROP_FRAME_WIDTH, 1920)
web_cam.set(cv2.CAP_PROP_FRAME_HEIGHT, 1080)

views = Blueprint('views', __name__)

scheduler = APScheduler()
scheduler.start()

global start_detection

global capture

capture = 0

image_file_path = ""

global total_detections

total_detections = 0


detection_done = False

start_detection = 0

ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


def enable_detection():
    global start_detection
    start_detection = 1


def increment_total_detections():
    global total_detections
    total_detections = total_detections + 1

def reset_total_detections():
    global total_detections
    total_detections = 0


def take_snapshot():
    global capture
    capture = 1


my_thread = threading.Thread()


def gen_frames():
    global start_detection
    global capture
    global detection_done
    while True:
        success, frame = web_cam.read()  # read the camera frame
        if not success:
            print("break")
            break
        else:
            if (start_detection):
                start_detection = 0
                file_path = ""
                file_path = os.path.sep.join(
                    ['website/static/session_shots', "shot_{}.jpg".format(str('abc').replace(":", '_'))])
                if (capture):
                    capture = 0
                    file_name = str(random.randint(0, 10)) + '.jpg'
                    print("FILE NAME ", file_name)
                    file_path = os.path.sep.join(
                        ['./website/static/temp/', file_name])
                    print("FILE PATH ", file_path)
                cv2.imwrite(file_path, frame)
                detection_done = detect_faces(file_path)
                print("Detection done")
                print("Picture Taken")
            else:
                ret, buffer = cv2.imencode('.jpg', frame)
                frame = buffer.tobytes()
                yield (b'--frame\r\n'
                       b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    data = Attendance.query.all()
    modules_query = Module.query.all()
    session_num = ""

    modules = [(curr.id, curr.module_name) for curr in modules_query]
    module_name = ""

    print("Modules: ", modules)

    if request.method == 'POST':

        if request.form['submit_button'] == 'Detect':

            flash('Detection has been started.', category='info')
            session_num = request.form['session_num']
            module_name = request.form['module_name']

            print("GET: ", session_num)

            print("POST: ", session_num)

            #module_name = db.session.query(Module).filter(Module.id ==selected_module).first()

            # clean_directory(directory='./website/static/query_faces/*')

            # If detection button clicked twice
            if scheduler.get_job('Detection'):
                flash("Detection already started.", category=info)
            else:
                scheduler.remove_all_jobs()

                def clear_query_faces():
                    scheduler.pause_job('clear')
                    clean_directory(directory='./website/static/query_faces/*')
                    scheduler.resume_job('detect')

                @copy_current_request_context
                def start_detection():
                    scheduler.pause_job('detect')
                    print("FACE DETECTION")
                    enable_detection()
                    scheduler.resume_job('rec')

                @copy_current_request_context
                def add_recognised_faces():

                    scheduler.pause_job('rec')

                    query_images = get_images('./website/static/query_faces/')
                    reference_images = get_images('./website/static/upload/')
                    print("PERFORMING FACE RECOGNITION")
                    record_array = preform_face_recognition(
                        query_images=query_images, reference_images=reference_images)
                    

                    if record_array is not None:
                        increment_total_detections()
                        for record in record_array:
                            img_file_path = record[0]
                            student_id = record[1]
                            check_in = record[2]

                            print("TOTAL DETECTIONS: ", total_detections)
                            #percentage = record[3]

                            #new_record = Attendance(img_file_path, student_id, datetime.datetime.now(), check_in, percentage)
                            exists = db.session.query(db.exists().where(
                                Attendance.student_id == student_id)).scalar()

                            try:
                                if not exists:
                                    new_record = Attendance(
                                        img_file_path, student_id, datetime.datetime.now(), 1, total_detections, 100)
                                    db.session.add(new_record)
                                    db.session.commit()
                                    print("Added to database Attendance")
                                    print("HEREE")
                                else:
                                    print("UPDATED DATE")

                                    
                                    student_current = db.session.query(Attendance).filter(
                                        Attendance.student_id == student_id).first()

                                    if check_in == True:
                                        db.session.query(Attendance).filter(Attendance.student_id == student_id).update(
                                            {'present_detections': student_current.present_detections + 1})

                                    db.session.query(Attendance).filter(Attendance.student_id == student_id).update(
                                        {'total_detections': total_detections})


                                    if student_current.present_detections == 0:
                                        percentage_attendance = 0
                                    else:
                                        percentage_attendance = round((student_current.present_detections/total_detections * 100),2)

                                    db.session.query(Attendance).filter(Attendance.student_id == student_id).update(
                                        {'percentage_attendance': percentage_attendance})

                                    db.session.query(Attendance).filter(
                                        Attendance.student_id == student_id).update({'date': datetime.datetime.now()})
                                    db.session.commit()

                            except exc.IntegrityError:
                                db.session.rollback()

                    scheduler.resume_job('clear')

                if scheduler.get_job('rec'):
                    print("sgsgsdgsdgsdgsd")
                else:
                    print("SCHEDULER STARTED")
                    scheduler.add_job(
                        id='rec', func=add_recognised_faces, trigger='interval', seconds=11)
                    scheduler.add_job(
                        id='clear', func=clear_query_faces, trigger='interval', seconds=5)
                    scheduler.add_job(
                        id='detect', func=start_detection, trigger='interval', seconds=10)
                    try:
                        db.session.query(Attendance).delete()
                        db.session.commit()
                        print("Attendance table cleared")
                        # return redirect('/')
                    except:
                        db.session.rollback()
        elif request.form['submit_button'] == 'Cancel':
            flash('Detection has been cancelled.', 'error')
            reset_total_detections()
            scheduler.remove_all_jobs()
            session_num = request.form['session_num']
            data = Attendance.query.all()
            module_name = request.form['module_name']
        elif request.form['submit_button'] == 'Refresh':
            session_num = request.form['session_num']
            module_name = request.form['module_name']
            data = db.session.query(Attendance).all()

Attendace-Face-Recognition-Web-App/website/templates/add_student.html
{% extends "base.html" %} {% block title %}Student{% endblock %} {% block content%}



    <link rel="stylesheet" type="text/css" rel="noopener" target="_blank" href="./static/add_student.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

    <div class="page_title_container" align="center">
        <h1>Student Register</h1>
    </div>

    <br />
    
    <div class ="student_container">
        <h3>Load Student Picture (Passport Style)</h3>
        {% if filename %}
            <div>
                <img src="{{ url_for('views.display_image', filename=filename) }}" width="200" height="200" alt="Uploaded student image">
            </div>
        {% endif %}
        <form method = "POST" action="" enctype="multipart/form-data">
        <dl>
            <p>
                <input
                name="file"
                type="file"
                class="form-control"
                autocomplete="off"
                value="{{ img_path }}"
                required
                >
            </p>
        </dl>
            <p>
            <input 
                name = "submit_button"
                type="submit" 
                value="Upload" 
                class="btn btn-info">
            </p>
        </form>

        
        
        <form method = "POST" action="" >
            <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" style="font-weight: bold; color: white;">
              Take Picture
            </button>
          
            <div class="collapse" id="collapseExample">
                <div class = "camera_stream">
                    <br />
                    <h3>Camera</h3>
                    <img src="{{ url_for('views.video_feed') }}" width="100%" alt="Video Streaming Window">
                  </div>
                  <br />
                  <input 
                  name = "submit_button"
                  type="submit" 
                  value="Capture" 
                  class="btn btn-info">
            </div>


        </form>
            
    
    <br />
    <div class ="student_details_cont">
        
        <form method ="POST" name="student_details">
            <h3>Enter Student Details</h3>

            <div class = "student_f_name">
                <label for="first_name">Student First Name</label>
                <input
                    type="text"
                    class="form-control"
                    id="first_name"
                    name="first_name"
                    value="{{ f_name }}"
                    placeholder="Enter Student First Name"
                    required
                />
            </div>
            <br />
            <div class = "student_l_name">
                <label for="last_name">Student Last Name</label>
                <input
                    type="text"
                    class="form-control"
                    id="last_name"
                    name="last_name"
                    value="{{ l_name }}"
                    placeholder="Enter Student Last Name"
                    required
                />
            </div>
            <br />
            <div class = "student_roll_no">
                <label for="email">Student ID Number</label>
                <input
                    type="text"
                    class="form-control"
                    id="student_id_num"
                    name="student_id_num"
                    value ="{{ student_roll_no }}"
                    placeholder="Enter Student ID Number"
                    required
                />
            </div>
            <br />
            <div class = "student_email">
                <label for="email">Student Email</label>
                <input
                    type="email"
                    class="form-control"
                    id="email"
                    name="email"
                    value ="{{ email }}"
                    placeholder="Enter Student Email"
                    required
                />
            </div>
            <br />
            <p>
                <input 
                    name = "submit_button"
                    type="submit" 
                    value="Add Student" 
                    class="btn btn-info">
            </p>

        </form>
    </div>
    <br />
    </div>



<div class="table_container">

    <table id = "data" class="table table-striped">
        <h3>View All Students</h3>
        <thead>
            <tr>
                <th>Student Image</th>
                <th>Student ID Number</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for row in data %}
            <tr>
                <td><img src={{ row['img_file_path'][8:] }} alt="" border=3 height=100 width=100></img></th>
                <td>{{ row['student_roll_no'] }}</td>
                <td>{{ row['f_name'] }}</td>
                <td>{{ row['l_name'] }}</td>
                <td>{{ row['email'] }}</td>
                <td>
                    <form action="{{ url_for('views.delete_entry', student_email=row['email']) }}" method=POST>
                        <button class="btn btn-info" style="background-color: red; border-color: red;"><i class="fa fa-trash" style="color: white;"></i></button>
                    </form>
                </td>
                    
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>    
</div>




    

<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;
    
    for (i = 0; i < coll.length; i++) {
      coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.maxHeight){
          content.style.maxHeight = null;
        } else {
          content.style.maxHeight = content.scrollHeight + "px";
        }
      });
    }
</script>


{% endblock %}

Attendace-Face-Recognition-Web-App/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="home" href="/add_student">Student Register</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert" style="text-align:center; font-weight:bold; font-size: larger;">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert" style="text-align:center; font-weight:bold; font-size: larger;">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.js"></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

Attendace-Face-Recognition-Web-App/website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}




<link rel="stylesheet" type="text/css" rel="noopener" target="_blank" href="./static/home.css">

<div class="cont">

  <form method="POST" name "form_id" action="{{ url_for('views.home') }}">

    <div class="form_elem">
      <div class="Nav">
        <h1 align="center">Face Recognition With Deep Learning</h1>
        <h3 align="center"> (MTCNN + ArcFace-Cos)</h3>
        <button type="submit" name="submit_button" class="btn btn-primary" value="Refresh">Refresh Attendance</button>
      </div>
      <div class="camera_stream">
        <h3>Web Cam Stream</h3>
        <img src="{{ url_for('views.video_feed') }}" width="100%" alt="Video Streaming Window">
      </div>
      <div class="class_details">
        <h3>Class Details</h3>
        <br />
        <div class="m_code">
          <label for="module_code">Module Code</label>
          <select name="modules_drop" value="modules" method="POST" class="selectpicker form-control"
            onchange="updateSelected(event)" required>
            {% for module in modules %}
            <option value="{{module}}">{{ module[0] }}</option>"
            {% endfor %}
          </select>
        </div>
        <br />
        <div class="m_name">
          <label for="module_name">Module Name</label>
          <input type="text" class="form-control" id="module_name" name="module_name" placeholder="Enter Module Name"
           value="{{ module_name }}" readonly />
        </div>
        <script>
          function updateSelected(event) {
            document.getElementById('module_name').value = (event.target.value).substr(13, event.target.value.length - 15);
          }
        </script>
        <br />
        <div class="session_num">
          <label for="session_num">Session Number</label>
          <input type="text" class="form-control" id="session_num" name="session_num" value="{{ session_num }}"
            placeholder="Enter Session Number" required />
        </div>

        <div class="button_cont" align="center">
          <button type="submit" name="submit_button" class="btn btn-primary" value="Detect">Start System</button>
          <button type="submit" name="submit_button" class="btn btn-primary" value="Cancel">Stop System</button>
          <button type="submit" name="submit_button" class="btn btn-primary" value="Export">Export To CSV</button>
        </div>

      </div>
    </div>

  </form>

  <table id="data" class="table table-striped" method="POST">
    
    <h3>View Session Attendance</h3>
    <br />
    <br />
    <thead>
      <tr>
        <th>Student Image</th>
        <th>Student ID Number</th>
        <th>Check In Date-Time</th>
        <th>Present Detections</th>
        <th>Total Detections</th>
        <th>Session Attendance (%)</th>
      </tr>
    </thead>
    <tbody>
      {% for row in data %}
      <tr>
        <td><img src={{ row['img_file_path'][10:] }} alt="" border=3 height=100 width=100></img></th>
        <td>{{ row['student_id'] }}</td>
        <td>{{ row['date'] }}</td>
        <td>{{ row['present_detections'] }}</td>
        <td>{{ row['total_detections'] }}</td>
        <td>{{ row['percentage_attendance'] }}</td>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

</div>

{% endblock %}

Attendace-Face-Recognition-Web-App/website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

Attendace-Face-Recognition-Web-App/website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}